#! /bin/zsh

# ls based
alias ls="ls --color"
alias ll="ls -l --color"
alias la="ls -la --color"
alias ..="cd .."

# git alias
alias gs="git status"
alias ga="git add"
alias gp="git push -u origin master"

# dmenu
#alias dmenu="dmenu -fn 'xft: Iosevka Term:size=20'"


gc(){
    git commit -m $1
}

gacp(){
    ga . && gc $1 && gp
}

brkbd(){
    brightnessctl --device='tpacpi::kbd_backlight' set $1 2&>/dev/null
}
