#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

$HOME/.config/polybar/launch.sh

if [ "$(xrandr | awk '/HDMI1/ {print $2}')" == "connected" ]; then
	bspc monitor eDP1 -d 6  7 8 9 0
	bspc monitor HDMI1 -d 1 2 3 4 5
else
	bspc monitor eDP1 -d I II III IV V VI VII VIII IX X
fi

bspc config border_width         1
bspc config window_gap           4
bspc config top_padding          0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

#polybar hidden when fullscreen for vlc, youtube, mpv ...
#find out the name of your monitor with xrandr
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_eDP1)
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI1)


bspc rule -a Gimp desktop='^8' state=floating follow=on
if [ "$(xrandr | awk '/HDMI1/ {print $2}')" == "connected" ]; then
    bspc rule -a Chromium desktop='^7'
else    
    bspc rule -a Chromium desktop='^2'
fi
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Citrix Workspace desktop='^8' follow=on state=fullscreen
bspc rule -a Wfica  desktop='^8' follow=on state=fullscreen
